### ISSUE TITLE
Default table sorting

### ISSUE THREAD

**Issue by SwyZeOff** [HelloSebastian/hello-bootstrap-table-bundle#23]
Hello,
Is there a way to sort a table by default on a given column? I've looked at all the options, but I can't find how to do this.

If I do this in my controller, my table is not sortable anymore :
```
$table->getQueryBuilder()
            ->addOrderBy("field", "desc");
```

Thanks

**Comment by HelloSebastian** [comment]
Hi,

thanks for the good question! In your HelloTable class you can override the `configureTableDataset` method and set the option. For example, if you have the column "date":

```php
public function configureTableDataset(OptionsResolver $resolver)
{
    parent::configureTableDataset($resolver);

    $resolver->setDefaults(array(
        'sort-name' => "date",
        'sort-order' => "desc" // or "asc"
    ));
}
```

The bootstrap-table documentation explains the fields: https://bootstrap-table.com/docs/api/table-options/#sortname and https://bootstrap-table.com/docs/api/table-options/#sortorder

You can use the `configureTableDataset` method to set any possible options of bootstrap-table, even if they are not yet included by default in HelloTable.

**Comment by SwyZeOff** [comment]
Thanks for your quick response!
I will add this directly in abstract class _HelloBootstrapTable_ :) 

```
protected function configureTableDataset(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(

            'sort-name' => null,
            'sort-order' => "asc",
        ));       
        $resolver->setAllowedTypes("sort-name", ["string","null"]);
        $resolver->setAllowedTypes("sort-order", ["string"]);
    }
```

**Comment by HelloSebastian** [comment]
It's better if you don't modify the `HelloBootstrapTable` abstract class. As soon as you reinstall your dependencies, the changes will be overwritten. (`composer install` / `composer udpate`)

Does the table work with the default value null? 

I'm already using this option in a couple of tables too, so I'll be happy to add the option to the `HelloBootstrapTable` class in the next days.

**Comment by HelloSebastian** [comment]
Perhaps I have not phrased myself well. By "override the method" I had meant that you override it in your *class*. Not *directly* in the abstract class itself.

**Comment by SwyZeOff** [comment]
Ahh Yes. Indeed, it's better that I do this in my class until you implement it in HelloBootstrapTable.
Yes, it works well with null value.

**Comment by SwyZeOff** [comment]
Do you think it is also possible to add an option to fill by default a cell, when the value is NULL?
I didn't find this option on the Bootstrap doc, but I think it must exist...

**Comment by HelloSebastian** [comment]
Each column has the "emptyData" option. As soon as the value is `null`, this text is displayed. The value from emptyData is output even if a relation does not exist.

I did not add the option from bootstrap-table, but added it myself for this bundle. Therefore you can't find it in the bootstrap-table documentation.

```php
$builder
    ->add('email', TextColumn::class, array(
        'title' => 'E-Mail',
        'emptyData' => 'No mail address'
    ))
    ->add('department.name', TextColumn::class, array(
        'title' => 'Department',
        'emptyData' => 'No department'
    ));
```

**Comment by SwyZeOff** [comment]
Thank you very much for your help ;)

**Comment by HelloSebastian** [comment]
The options were added by the PR #24. I have just published the new v.0.7.0 release. Update the bundle (`composer require hello-sebastian/hello-bootstrap-table-bundle`. 

Please check the readme file for more information: https://github.com/HelloSebastian/hello-bootstrap-table-bundle#default-table-sorting
