### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by funmobi** [HelloSebastian/hello-bootstrap-table-bundle#32]
Hello,
Is there any way to translate column titles or button titles?

**Comment by HelloSebastian** [comment]
Hello,

do you mean using Symfony tanslation bundle or just changing certain texts statically in another language?

**Comment by HelloSebastian** [comment]
Well, this is something I haven't thought of before. But of course it makes sense to include translation like Twig (which is already there). Maybe Twig and Translation should be optional.

It is true that with the existing architecture it is difficult to include dependencies in the HelloBootstrapTable classes. When I needed a dependency once, I integrated it into the table class through the `options` from the Controller.

Another option is to use methods for the dependencies. I had tried this once, but it didn't work directly, so I didn't follow it up. (https://symfony.com/doc/current/service_container/calls.html)

Here is an example with the options:

```php
// Controller

public function index(Request $request, HelloBootstrapTableFactory $tableFactory, TranslatorInterface $translator): Response {
    $tableFactory->create(YourTable::class, [
        "translator" => $translator
    ]);

    // ...
}

// YourTable

class ComponentShadowTable extends HelloBootstrapTable
{
    protected function buildColumns(ColumnBuilder $builder, $options)
    {
        /** @var TranslatorInterface $translator */
        $translator = $options["translator"];

        // ...
    }
}
```

I hope this helps you.

**Comment by funmobi** [comment]
Hello @HelloSebastian. Yes, this solves my problem. Thank you very much!

**Comment by HelloSebastian** [comment]
You are welcome
