### ISSUE TITLE
Symfony >= 5.4 remove deprecations

### ISSUE THREAD

**Issue by funmobi** [HelloSebastian/hello-bootstrap-table-bundle#33]
Hello,
Could you please remove the deprecation and ensure compatibility with Symfony >= 5.4?

`Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "HelloSebastian\HelloBootstrapTableBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Comment by HelloSebastian** [comment]
Hey, I added to all methods types in the pull request #35. So the error should be fixed. However, there is a **breaking change** in the PR. The methods in the `HelloBootstrapTable` class have also been given types, so changes need to be made here in your classes.

For more info, check out the PR.

If it's still relevant to you, feel free to test the master branch.
